name: Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      lts: 5.6.0
      default_os: alpine3.15
      image_name: lunik/ansible
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - 5.6.0
        python:
          - 3.10.4
        os:
          - slim-bullseye
          - alpine3.15
        platform:
          - linux/amd64,linux/arm64/v8
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          cache: 'pip'

      - name: Setup requirements
        run: pip install -r requirements.txt

      - name: Template build files
        run: |
          python3 scripts/render_templates.py \
          '${{ toJSON(matrix) }}' \
          dist/${{ matrix.ansible }}_${{ matrix.os }}

      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: # optional
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ env.image_name }}
          labels: |
            ANSIBLE_VERSION=${{ matrix.ansible }}
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}}-${{ matrix.os }},value=${{ matrix.ansible }}
            type=semver,pattern={{major}}.{{minor}}-${{ matrix.os }},value=${{ matrix.ansible }}
            type=semver,pattern={{major}}-${{ matrix.os }},value=${{ matrix.ansible }}
            type=semver,pattern={{version}},value=${{ matrix.ansible }},enable=${{ matrix.os == env.default_os }}
            type=semver,pattern={{major}}.{{minor}},value=${{ matrix.ansible }},enable=${{ matrix.os == env.default_os }}
            type=semver,pattern={{major}},value=${{ matrix.ansible }},enable=${{ matrix.os == env.default_os }}
            type=raw,value=latest,enable=${{ matrix.ansible == env.lts && matrix.os == env.default_os }}
            type=raw,value=alpine,enable=${{ matrix.ansible == env.lts && contains(matrix.os, 'alpine') }}
            type=raw,value=debian,enable=${{ matrix.ansible == env.lts && contains(matrix.os, 'slim') }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.8.0
        with:
          cache-from: ${{ env.image_name }}:${{ matrix.ansible }}-${{ matrix.os }}
          context: dist/${{ matrix.ansible }}_${{ matrix.os }}
          platforms: ${{ matrix.platform }}
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
