name: Security Scan

on:
  schedule:
  - cron: "0 3 * * 0"

  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      image_name: lunik/ansible
    strategy:
      matrix:
        ansible:
          - 5.2.0
          - 4.10.0
        python:
          - 3.10.2
        os:
          - slim-bullseye
          - alpine3.15
    steps:
      - uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.image_name }}:${{ matrix.ansible }}-${{ matrix.os }}
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-results.sarif
          severity: HIGH,CRITICAL

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'